sandboxer: performing refactor of main scripts - replace "test" command with more safe and fast "[[ ]]" bash construct

diff --git a/Sandboxer/includes/channel-open.sh.in b/Sandboxer/includes/channel-open.sh.in
--- a/Sandboxer/includes/channel-open.sh.in
+++ b/Sandboxer/includes/channel-open.sh.in
@@ -3,20 +3,19 @@
 # clear internal variable
 channel=""
 
-if [ "${cfg[$exec_profile.exclusive]}" = "true" ]; then
- test "$exec_profile" = "profile" && req_channel="$profile" || req_channel="$exec_profile"
- if [ -p "$basedir/control/$req_channel.in" ] || [ -p "$basedir/control/$req_channel.out" ]; then
-  log "exclusive exec-profile $req_channel already running"
-  teardown 1
- fi
+if [[ ${cfg[$exec_profile.exclusive]} = true ]]; then
+  [[ $exec_profile = profile ]] && req_channel="$profile" || req_channel="$exec_profile"
+  if [[ -p $basedir/control/$req_channel.in || -p $basedir/control/$req_channel.out ]]; then
+    log "exclusive exec-profile $req_channel already running"
+    teardown 1
+  fi
 else
- req_channel=""
+  req_channel=""
 fi
 
-#test source-checksum, in order to verify that commander and executor modules was built from the same source files
+#check source-checksum, in order to verify that commander and executor modules was built from the same source files
 2>/dev/null "$commander" "$basedir/control" control "${cfg[sandbox.setup.security_key]}" 240
-test "$?" != "0" && log "executor's build version mismatch detected. you must update executor module used for this sandbox: run sandboxer-download-extra.sh" && teardown 1
+[[ $? != 0 ]] && log "executor's build version mismatch detected. you must update executor module used for this sandbox: run sandboxer-download-extra.sh" && teardown 1
 
 channel=`2>/dev/null "$commander" "$basedir/control" control "${cfg[sandbox.setup.security_key]}" 0 "$req_channel"`
-test -z "$channel" && log "failed to create new session to run selected exec-profile" && teardown 1
-
+[[ -z $channel ]] && log "failed to create new session to run selected exec-profile" && teardown 1
