feature-post-xpra.sh.in: work in progress

diff --git a/Sandboxer/includes/feature-post-xpra.sh.in b/Sandboxer/includes/feature-post-xpra.sh.in
--- a/Sandboxer/includes/feature-post-xpra.sh.in
+++ b/Sandboxer/includes/feature-post-xpra.sh.in
@@ -21,43 +21,44 @@ if [[ ! -p $basedir/control/xpra.in || ! -p $basedir/control/xpra.out ]]; then
   . "$includes_dir/channel-open.sh.in"
   exec_bg="true"
   exec_bg_pid=""
-  exec_log_out="$basedir/xpra-daemon.stdout"
-  exec_log_err="$basedir/xpra-daemon.stderr"
   . "$includes_dir/run-profile.sh.in"
+  wait "$exec_bg_pid"
+  if [[ $? != 0 ]]; then
+    log "xpra exec profile startup failed. executor log output:"
+    cat $basedir/control/xpra.log
+    teardown 1
+  fi
   #wait for output. TODO: this is a copy from dbus daemon, change it to xpra information output
-  xpra_wait=400
-  while [[ $xpra_wait -ge 1 ]]
-  do
-    if [[ -f $basedir/xpra-daemon.stdout && `wc -l <"$basedir/xpra-daemon.stdout"` = 2 ]]; then
-      mapfile -t -n 1 xpra_env_a <"$basedir/xpra-daemon.stdout"
-      if [[ "${xpra_env_a[0]}" =~ ^unix:.*,guid=.{32,32}$ ]]; then
-        xpra_env="${xpra_env_a[0]}"
-        break
-      fi
-    fi
-    sleep 0.025
-    xpra_wait=$((xpra_wait-1))
-  done
-  #detach commander for xpra session
-  2>/dev/null kill -SIGUSR2 $exec_bg_pid
-  check_errors "failed to send detach command to xpra-session commander"
+  #xpra_wait=400
+  #while [[ $xpra_wait -ge 1 ]]
+  #do
+  #  if [[ -f $basedir/xpra-daemon.stdout && `wc -l <"$basedir/xpra-daemon.stdout"` = 2 ]]; then
+  #    mapfile -t -n 1 xpra_env_a <"$basedir/xpra-daemon.stdout"
+  #    if [[ "${xpra_env_a[0]}" =~ ^unix:.*,guid=.{32,32}$ ]]; then
+  #      xpra_env="${xpra_env_a[0]}"
+  #      break
+  #    fi
+  #  fi
+  #  sleep 0.025
+  #  xpra_wait=$((xpra_wait-1))
+  #done
   #TODO: xpra-watchdog
-  (. "$includes_dir/xpra-watchdog.sh.in" ) &>"$basedir/xpra-watchdog.log" &
+  #(. "$includes_dir/xpra-watchdog.sh.in" ) &>"$basedir/xpra-watchdog.log" &
 elif [[ -p $basedir/control/xpra.in && -p $basedir/control/xpra.out ]]; then
   # just read already created xpra-daemon.stdout
   mapfile -t -n 1 xpra_env_a <"$basedir/xpra-daemon.stdout"
   #TODO: this is a copy from dbus daemon, change it to xpra information output parsing
   #TODO: read DISPLAY env variable for sandbox
   #TODO: read connection parameters
-  if [[ "${xpra_env_a[0]}" =~ ^unix:.*,guid=.{32,32}$ ]]; then
-    xpra_env="${xpra_env_a[0]}"
-  fi
+  #if [[ "${xpra_env_a[0]}" =~ ^unix:.*,guid=.{32,32}$ ]]; then
+  #  xpra_env="${xpra_env_a[0]}"
+  #fi
 fi
 
 # check, do we succeed with xpra startup, and do not procced if we are not
-if [[ -z $xpra_env ]]; then
-  log "failed to get valid xpra-daemon env parameters"
-  teardown 1
-fi
+#if [[ -z $xpra_env ]]; then
+#  log "failed to get valid xpra-daemon env parameters"
+#  teardown 1
+#fi
 
-extra_env_set_add "DISPLAY" "$xpra_env"
+#extra_env_set_add "DISPLAY" "$xpra_env"
