feature-post-x11host.sh.in: add slightly more debug

diff --git a/Sandboxer/includes/feature-post-x11host.sh.in b/Sandboxer/includes/feature-post-x11host.sh.in
--- a/Sandboxer/includes/feature-post-x11host.sh.in
+++ b/Sandboxer/includes/feature-post-x11host.sh.in
@@ -21,9 +21,11 @@ if [ ! -z "$x11host_pre_triggered" ]; then
   exec_log_err="$basedir/x11util.stderr"
   . "$includes_dir/run-profile.sh.in"
   wait "$exec_bg_pid"
-  if [ "$?" != "0" ]; then
-    log "x11util was failed! stderr output:"
+  x11util_ec="$?"
+  if [ "$x11util_ec" != "0" ]; then
+    log "x11util was failed! error code=$x11util_ec, stderr output:"
     cat "$basedir/x11util.stderr"
+    # TODO: perform shutdown of currently running master executor and other sessions
     teardown 1
   fi
   rm "$basedir/extra/x11util"
