feature-post-dbus.sh.in: use new fallback method for quit in case of errors

diff --git a/Sandboxer/includes/feature-post-dbus.sh.in b/Sandboxer/includes/feature-post-dbus.sh.in
--- a/Sandboxer/includes/feature-post-dbus.sh.in
+++ b/Sandboxer/includes/feature-post-dbus.sh.in
@@ -3,6 +3,11 @@
 # dbus feature
 
 if [[ ! -p $basedir/control/dbus.in || ! -p $basedir/control/dbus.out ]]; then
+  [[ $post_feature_failed = 0 ]] && (
+  #redefine teardown, so it will not accidentally remove sandboxer lock
+  teardown() {
+    exit 1
+  }
   #remove old dbus-daemon.stdout
   rm -f "$basedir/dbus-daemon.stdout"
   check_errors
@@ -16,7 +21,7 @@ if [[ ! -p $basedir/control/dbus.in || ! -p $basedir/control/dbus.out ]]; then
       [[ -x ${cfg[tunables.features.dbus_search_prefix]}$hint/dbus-daemon ]] && cfg[$exec_profile.exec]="$hint/dbus-daemon" && break
       # log "no dbus-daemon binary at ${cfg[tunables.features.dbus_search_prefix]}$hint" # debug
     done
-    [[ -z ${cfg[$exec_profile.exec]} ]] && log "dbus-daemon binary not found!" && teardown 1
+    [[ -z ${cfg[$exec_profile.exec]} ]] && log "dbus-daemon binary not found!" && post_feature_failed=1
   fi
   . "$includes_dir/channel-open.sh.in"
   exec_bg="true"
@@ -28,12 +33,9 @@ if [[ ! -p $basedir/control/dbus.in || ! -p $basedir/control/dbus.out ]]; then
   dbus_wait=400
   while [[ $dbus_wait -ge 1 ]]
   do
-    if [[ -f $basedir/dbus-daemon.stdout && `wc -l <"$basedir/dbus-daemon.stdout"` = 2 ]]; then
+    if [[ -f $basedir/dbus-daemon.stdout ]]; then
       mapfile -t -n 1 dbus_env_a <"$basedir/dbus-daemon.stdout"
-      if [[ "${dbus_env_a[0]}" =~ ^unix:.*,guid=.{32,32}$ ]]; then
-        dbus_env="${dbus_env_a[0]}"
-        break
-      fi
+      [[ "${dbus_env_a[0]}" =~ ^unix:.*,guid=.{32,32}$ ]] && break
     fi
     sleep 0.025
     dbus_wait=$((dbus_wait-1))
@@ -41,19 +43,21 @@ if [[ ! -p $basedir/control/dbus.in || ! -p $basedir/control/dbus.out ]]; then
   #detach commander for dbus session if it is running
   2>/dev/null kill -SIGUSR2 $exec_bg_pid
   check_errors "failed to send detach command to dbus-session commander"
+  exit 0
+  ) || post_feature_failed=1
   add_watchdog_profile "dbus"
-elif [[ -p $basedir/control/dbus.in && -p $basedir/control/dbus.out ]]; then
-  # just read already created dbus-daemon.stdout
-  mapfile -t -n 1 dbus_env_a <"$basedir/dbus-daemon.stdout"
-  if [[ "${dbus_env_a[0]}" =~ ^unix:.*,guid=.{32,32}$ ]]; then
-    dbus_env="${dbus_env_a[0]}"
-  fi
+fi
+
+# just read already created dbus-daemon.stdout
+mapfile -t -n 1 dbus_env_a <"$basedir/dbus-daemon.stdout"
+if [[ "${dbus_env_a[0]}" =~ ^unix:.*,guid=.{32,32}$ ]]; then
+  dbus_env="${dbus_env_a[0]}"
 fi
 
 # check, do we succeed with dbus startup, and do not procced if we are not
 if [[ -z $dbus_env ]]; then
   log "failed to get valid dbus-daemon env parameters"
-  teardown 1
+  post_feature_failed=1
+else
+  extra_env_set_add "DBUS_SESSION_BUS_ADDRESS" "$dbus_env"
 fi
-
-extra_env_set_add "DBUS_SESSION_BUS_ADDRESS" "$dbus_env"
