find-lua-helper service script updated and simplified

diff --git a/Sandboxer/includes/find-lua-helper.bash.in b/Sandboxer/includes/find-lua-helper.bash.in
--- a/Sandboxer/includes/find-lua-helper.bash.in
+++ b/Sandboxer/includes/find-lua-helper.bash.in
@@ -2,29 +2,13 @@
 
 bash_lua_helper=""
 
-find_lua_user_dir="$@"
-find_lua_helper_dir="$( cd "$( dirname "$BASH_SOURCE" )" && pwd )"
+for hint in "$@"
+do
+ #debug
+ #echo "probing $hint"
+ test -f "$hint/lua-helper.bash.in" && bash_lua_helper="$hint/lua-helper.bash.in" && break
+done
 
-find_in_dir () {
- test -z "$@" && return 1
- if [ -f "$@/lua-helper.bash.in" ]; then
-  bash_lua_helper="$@/lua-helper.bash.in"
-  return 0
- else
-  return 1
- fi
-}
-
-find_in_dir "$find_lua_user_dir" || find_in_dir "$find_lua_helper_dir" || find_in_dir "$find_lua_helper_dir/../BashLuaHelper"
-
-if [ -z "$bash_lua_helper" ]; then
- echo "lua-helper.bash.in not found!"
- exit 1
-fi
+test -z "$bash_lua_helper" && echo "lua-helper.bash.in not found!" && exit 1
 
 bash_lua_helper=`realpath "$bash_lua_helper"`
-
-unset find_lua_helper_dir
-unset find_lua_user_dir
-unset -f find_lua_in_dir
-
